### ISSUE TITLE
Outrageous integration with laravel for fun and profit

### ISSUE THREAD

**Issue by Lelectrolux** [jenshaase/phel-lang#10]
Hi, I love the project, I'm having a lot of fun tinkering with it, thanks a lot.

---

Right now, I'm looking at how deep I can go trying to use phel as laravel controllers.  
Why ? Just because it's fun.

Getting it to run was really easy, just add the package to composer and install, slap

```php
$this->app->singleton(Runtime::class, function ($app) {
    $runtime = Runtime::initialize();
    $runtime->addPath('app\\', [app_path()]);
    $runtime->loadNs('phel\core');
    return $runtime;
});
```

into `AppServiceProvider->register`, add a route macro for convenience 

```php
$router = $this->app['router'];
$router::macro('phel', function ($path, $controller) use ($router) {
    return $router->get($path, function (Runtime $runtime) use ($controller) {
        $runtime->loadNs("app\\Http\\Controllers\\$controller");
    });
});
```

into `AppServiceProvider->boot`, and now I can match urls to phel script files with 

```php
Route::phel('/foo', 'bar'); // matches "example.com/foo" to `App\Http\Controllers\bar.phel`
```

```commonlisp
(ns app\Http\Controllers\bar)

(print "Phel sends his regards.")
```

And it works... Kinda.

---

I have one issue and a few questions or suggestions

### ERROR : output contains some error message

Phel sends his regards.&lt;p&gt;Unterminatend list&lt;br/&gt;in &lt;em&gt;C:\laragon\www\laraphel\app\Http\Controllers\bar.phel:4&lt;/em&gt;&lt;/p&gt;&lt;pre&gt;&lt;code&gt;4| <br/>   <br/>&lt;/pre&gt;&lt;/code&gt;

Even if I remove `(print "Phel sends his regards.")`, I still get this error message.

###  Current implementation uses php's `exit` liberally

This prevents any one to do anything after phel has run, or even using ob_ functions to work with output.

### Is there any way to pass a few global php variables to phel scripts ?

Something like $runtime->loadNs('phel\core', ['request' => $request, ...])

I was able to get Laravel app/container and assign it in phel, as it's a singleton, but it can be quite verbose quite fast.

```
(ns app\boot
  (:use \Illuminate\Foundation\Application))

(def app (php/:: Application (getInstance)))

(defn resolve [binding]
  (php/-> app (make binding)))
```

### Is there a way to call global php functions in phel ?

I don't see anything in the docs on that front, it only works with object or classes as far as I can tell.

I wanted to convert `view('welcome')` in php to something akin to `(php\call view "welcome")` in Phel. So far I have to redefine it in Phel

```
# I'm using my previously defined resolve function
(defn view [viewfile]
  (php/-> (resolve "view") (make viewfile)))
```

### Is there any way to return something from phel to php ?

Even if phel didn't "hard exit" the script, I don't know how I can pass something back to the php side of things... `loadNs` return a boolean, and ob_ functions can't really deal with anything more than output.

**Comment by Lelectrolux** [comment]
(But I do know I'm trying to do stupid stuff just for the sake of it, so just tell me if you don't want to deal with either this or crazy me \^\^, no hard feelings)

**Comment by jenshaase** [comment]
This is cool!

I will try to reproduce it on my own. Regarding your questions

> ERROR : output contains some error message

Will try to reproduce it and than fix this.

> Current implementation uses php's exit liberally

Yes, that definitely needs to be changed.

> Is there any way to pass a few global php variables to phel scripts ?

No, that will not work. `loadNs` is more like `require <file>` in PHP.

> Is there a way to call global php functions in phel ?

Yes that is quite easy. Just do `(php/<my-function-name> <arg1> <arg2> ...)`. For example `(php/strlen "test")`. I added this to the documentation: https://phel-lang.org/documentation/php-interop/

> Is there any way to return something from phel to php ?

No, `loadNs` returns true if it was possible to load file and false otherwise.

Maybe I have to add that I had no intention to embed Phel into an existing PHP app like you did. But still impressive that you made it this far! Instead, I focused more on the other part - integrating existing PHP Libs into Phel.
I have not so much experience in Laravel, but I will try to build an example app in Phel that uses Laravel and post the code here.

**Comment by mabasic** [comment]
It would be cool if it would be possible to make a complete circle with php and phel. 

eg. Start in php, call phel code/script, use php class in phel, return value from from phel to php, continue in php etc...

This is probably impossible and probably won't be used at all 😁, but sound nice.

It would certainly allow more php/laravel developers to experience fp while remaining in the php world. It depends on what you want to do with Phel. If you want Phel to be the primary language  then doing this makes no sense, not sure

**Comment by Lelectrolux** [comment]
@jenshaase

> Yes that is quite easy. Just do (php/<my-function-name> <arg1> <arg2> ...). For example (php/strlen "test"). I added this to the documentation: https://phel-lang.org/documentation/php-interop/

D'oh... Should have tested that on my own... Thanks

> Maybe I have to add that I had no intention to embed Phel into an existing PHP app like you did.

Yeah, I expected that \^\^. I know this is just me fooling around. But it doesn't seem that impossible.
I'm pretty sure I could hack it in a roundabout way with a static value bag.

Something like 

```php
// Value bag
class InOut
{
   public static $in = [];
   public static $out;
}

// Script, typically a controller
InOut::$in = ['request' => $request, ...];
$runtime->loadNs('app/controller');
$returnValue = InOut::$out;
```

```
(ns app/controller (:use InOut))

// grab from InOut::$in
// do stuff
// put return value to InOut::$out
```

> I have not so much experience in Laravel, but I will try to build an example app in Phel that uses Laravel and post the code here.

I will publish a repo with my code or at least a gist of the few modified files if you want. I'll do that today.

**Comment by Lelectrolux** [comment]
> Will try to reproduce it and than fix this.

I got what it was.

Extra empty line at the end of the file added on save by my editor...

I just added
```
[*.phel]
insert_final_newline = false
```
to my .editorconfig

**Comment by jenshaase** [comment]
> Extra empty line at the end of the file added on save by my editor...

Fixed this bug.

**Comment by Lelectrolux** [comment]
Okay, I have a "working" in and out solution.

I'm using a static input bag, and sidestepping the exit calls by throwing an exception as an "end-script" call.

```php
class Input
{
    private static array $in = [];

    public static function clear(): void
    {
        self::$in = [];
    }

    public static function set(string $key, $value): void
    {
        self::$in[$key] = $value;
    }

    public static function get(string $key)
    {
        return self::$in[$key] ?? null;
    }

    public static function all()
    {
        return self::$in;
    }
}

class Output extends Exception
{
    public $output;

    public static function toPhp($output)
    {
        $e = new self();
        $e->output = $output;
        throw $e;
    }
}

/* $value = runPhelScript('app\foo', ['request' => request()]); */
function runPhelScript(string $script, array $inputs = [])
{
    $runtime = resolve(Runtime::class);

    Input::clear();
    foreach ($inputs as $key => $value) {
        Input::set($key, $value);
    }
    
    try {
        $runtime->loadNs($script);
    } catch (Output $exception) {
        return $exception->output;
    }
}
```

```
# Helpers
(ns app\core
  (:use \Output)
  (:use \Input))

(defn get-from-php [key]
  (php/:: Input (get key)))

(defn return-to-php [returnValue]
  (php/:: Output (toPhp returnValue)))
```

It's an ugly baby, but it is alive \^\^

Still quite dumb, tho

**Comment by jenshaase** [comment]
Little update on this.

> Current implementation uses php's exit liberally

I resolve the following bug.
