### ISSUE TITLE
Create NodeEnvironmentInterface

### ISSUE THREAD

**Issue by Chemaclass** [jenshaase/phel-lang#128]
Do some research and look if it makes sense to create a `NodeEnvironmentInterface`. I think it does, but we should double-check that. 

In case we want to add that interface: look for every place where it depends on the `NodeEnvironment` and invert it by depending on a `NodeEnvironmentInterface` instead.

Acceptance Criteria:

- The place to create that interface might be for now the same where the `NodeEnvironment` is.
- The `NodeEnvironmentInterface` must contain the public method that is truly part of the public API of the `NodeEnvironment`. 

You can start by defining all of the public used functions from the concrete class and figure out if they make sense as part of the interface or not. (usually yes; sometimes/rarely nope).

**Comment by jenshaase** [comment]
Makes sense to create a `NodeEnvironmentInterface`

**Comment by jenshaase** [comment]
Closed with PR #132
