### ISSUE TITLE
Add the "phpdoc_line_span" to the CS Fixer

### ISSUE THREAD

**Issue by Chemaclass** [jenshaase/phel-lang#130]
## Description

According to what we agreed on https://github.com/jenshaase/phel-lang/pull/124
We decided to add this extra CS Fixer Rule: https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_line_span.

## Acceptance Criteria

- Add the new CS Fixer Rule
- Apply the fix to the whole project

**Comment by JesusValera** [comment]
I will do it!
