### ISSUE TITLE
Could we adapt this code style?

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#137]
[Hy Style Guide](https://docs.hylang.org/en/master/style-guide.html)

I have formatted code in this [PR](https://github.com/jenshaase/phel-lang/pull/136/files#diff-c9c26e3060e05a86c32176fd950e1cd97959abd0ba88bd4fd0361ed085aa3e7f) according to this style guide and it looks good and logical to me.

What do you think? Could we add this to the documentation and then in the future build a code formatter around this?

**Comment by jenshaase** [comment]
You can use it as reference but I will currently not define a concrete coding style. A concrete coding style only makes sense if we have a tool to check against it.

**Comment by mabasic** [comment]
I will do some research on the subject of building a code formatting tool.

Do you know of any lisp language that has a code formatter?

**Comment by jenshaase** [comment]
Yes there is https://github.com/weavejester/cljfmt but it requires some additional libraries to parse and annotate the code. It is definitely not an easy task. If I find some time in the next days I can create a concept for it.

**Comment by jenshaase** [comment]
To write a formatter you first need to build a so called bidirectional parser. This parser is able to parser Phel code. The result of the parser is parse tree. However, the parse tree not only contains information to compile to the target language but also all whitespaces and comments in the file. Thereby, it is possible to print the source code in the same way it was read from the file. An example for that is the rosyln compiler for dotnet (https://github.com/dotnet/roslyn/blob/master/docs/wiki/Getting-Started-C%23-Syntax-Analysis.md)

Having such a bidirectional parser the formatter just needs to manipulate the parse tree according to the given rules.

**Comment by jenshaase** [comment]
Hi @mabasic,

I found some time to build such a bidirectional Parser. Have a look at this class:
https://github.com/jenshaase/phel-lang/blob/master/src/php/Compiler/Parser.php

Please also have a look a the tests to see how it works.

**Comment by mabasic** [comment]
@jenshaase O.o will take a look tonight.

**Comment by mabasic** [comment]
@jenshaase I took a look. It took me some time to figure out what it does (The tests helped, thank you).

I assume that if I feed it a phel source file, It will return a tree of things inside that file. Once I obtain that tree, I could write a formatter that will modify that tree according to some rules, and possible find a way to revert back to phel source code and overwrite the file.

Am I right?

**Comment by jenshaase** [comment]
Correct!

**Comment by jenshaase** [comment]
Just for reference. Here is another Lisp style code formatter in Janet: https://github.com/janet-lang/spork/blob/master/spork/fmt.janet

**Comment by mabasic** [comment]
Thank you. I was studying Janet these past few days. Will take a look.

**Comment by jenshaase** [comment]
I investigated some time on the weekend on this topic. I have a concept and little bit of code on how to build a formatter. Hopefully it turns out good. I will keep you updated if I have a first working version.

**Comment by mabasic** [comment]
> @jenshaase I took a look. It took me some time to figure out what it does (The tests helped, thank you).
> 
> I assume that if I feed it a phel source file, It will return a tree of things inside that file. Once I obtain that tree, I could write a formatter that will modify that tree according to some rules, and possible find a way to revert back to phel source code and overwrite the file.
> 
> Am I right?

We could use this bidirectional Parser to generate documentation for Phel libraries? Something like go lang has or deno.

**Comment by jenshaase** [comment]
> We could use this bidirectional Parser to generate documentation for Phel libraries? Something like go lang has or deno.

No. There are not enough information in the parse tree. But have a look at https://github.com/jenshaase/phel-lang/blob/master/doc/build-api-page.php on how I generate the API Docs for the website.

**Comment by jenshaase** [comment]
There is a first draft of a code formatter now. You can use it with `phel fmt <filename>`.

I will close this ticket now. If there are any problems with the formatter please make new issues.

**Comment by mabasic** [comment]
Nice, will take a look asap. 👍
