### ISSUE TITLE
Add Psalm to the project

### ISSUE THREAD

**Issue by Chemaclass** [jenshaase/phel-lang#14]
I strongly suggest installing [psalm](https://psalm.dev/docs/running_psalm/installation/). 
It works like charm. 

## Supported annotations: 

https://psalm.dev/docs/annotating_code/supported_annotations/

Some of my favorite annotations are: `@psalm-immutable`, `@psalm-pure`, `@psalm-return list<YourType>`, and much more!

**Comment by jenshaase** [comment]
It already is installed (see composer.json and psalm.xml) and I make it almost work to level 3. It adds a lot of value but also has some false positive :(

**Comment by Chemaclass** [comment]
Achso! My bad, I didn't look at the `composer.json`, I thought you didn't have it because I didn't see any `@psalm-{annotation}` (well, actually three of this `@psalm-suppress`). Did you try to reduce the number of false positives by using more psalm annotations? 
Indeed, false positives are noise, but I'm sure we can get rid of them (at least most of them) by adding annotations or finding another workaround, which sometimes leads to better design or solution :)
