### ISSUE TITLE
Standarize Interfaces through the project

### ISSUE THREAD

**Issue by JesusValera** [jenshaase/phel-lang#145]
I notice the interfaces from `Phel\Lang` use the Hungarian nomenclature, which means, instead of `MetaInterface`, they are called `IMeta`.

I would suggest renaming all of them from `I{Class}` to `{Class}Interface`.

<img width="289" alt="Screenshot 2020-12-31 at 17 05 29" src="https://user-images.githubusercontent.com/6381924/103417290-6828b380-4b8a-11eb-8d47-24d347c5447a.png">

The purpose of the issue is to standardized the interface names through the whole project, besides, I think it could be a good idea to create an ADR with this specification.

What do you think @jenshaase @Chemaclass?

**Comment by jenshaase** [comment]
Is there as PHP-CS-Fixer rule that can we use?

**Comment by Chemaclass** [comment]
About using PHP CS Fixer for this rule, this is what the cs fixer author said in 2016:
> Very risky and it isn't really code style but rather naming conversion ([source](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2161#issuecomment-242916426))

I like the idea pretty much. I would use the `Interface` suffix for all interfaces in order to normalize them in the project. 
I think an ADR with this info would be good for the project as well, because this is a pure naming convention. 
My vote is 👍🏼

**Comment by jenshaase** [comment]
Ok, I would recommend to define a naming conversion for every class, function, trait, etc. then:

* Use camelCase for PHP variables, function and method names, arguments
* Use UpperCamelCase for class names
* Suffix interfaces with `Interface`
* Suffix traits with `Trait`
* Suffix exceptions with `Exception`
* Prefix abstract classes with `Abstract`

**Comment by Chemaclass** [comment]
Yes, this is actually the actual Symfony naming convention. I am super ok with this :) https://symfony.com/doc/current/contributing/code/standards.html
And yeah, it would be nice to have it our adrs

**Comment by jenshaase** [comment]
Closed with PR #147
