### ISSUE TITLE
Mapcat is not working with empty arrays or tuples

### ISSUE THREAD

**Issue by jenshaase** [jenshaase/phel-lang#15]
Following code fails

```
(mapcat identity @[])
```

which is equivalent to 

```
(apply concat (map f xs))
```

However, `concat` requires at least two arguments but there is only one

**Comment by Chemaclass** [comment]
@jenshaase What would be the assert test that should pass for this `mapcat` failing case: `(mapcat identity @[])`?

It would be helpful to understand what do you exactly mean if you write the specific assertion that should pass from `tests/phel/test/core.phel`

**Comment by jenshaase** [comment]
Fixed
