### ISSUE TITLE
Set should not have keys returned

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#165]
Examples:

```
>>> (foreach [k v (set 1 2 3)] (println k v))
1 1
2 2
3 3
nil
```

```
>>> (foreach [k v (set 1 2 (set 1 2))] (println k v))
1 1
2 2
000000000e2bb3150000000038a930db (set 1 2)
nil
```

I am assuming that those keys should not be displayed?

I was expecting to get keys similar to what array returns:

```
>>> (foreach [k v @[1 2 3]] (println k v))
0 1
1 2
2 3
nil
```

**Comment by jenshaase** [comment]
I fixed this now.

**Comment by mabasic** [comment]
> I fixed this now.

Great, I'm going to refactor the encode function asap. Maybe implement the decode function also if I find the time tonight.

**Comment by mabasic** [comment]
@jenshaase It seems there is a bug in the fix for this.

When I run `(foreach [k v (set 1 2 (set 1 2))] (println k v))`, I get:

```
>>> (foreach [k v (set 1 2)] (println k v))
0 1
0 2
nil
```

Shouldn't it be?

```
0 1
1 2
nil
```
