### ISSUE TITLE
Unifying the code style with "PHP CS Fixer"

### ISSUE THREAD

**Issue by Chemaclass** [jenshaase/phel-lang#17]
Having a unified code style will allow every contributor to write code with the same style everywhere.

This is a great tool for it: https://github.com/FriendsOfPHP/PHP-CS-Fixer 

A template example extracted from PHPUnit: https://github.com/sebastianbergmann/phpunit/blob/master/.php_cs.dist

**Comment by jenshaase** [comment]
Sounds good. I look at it, but there are so many changes that I have to figure out a ruleset that isn't doing so many changes and than move this in the direction of PSR-12.

**Comment by jenshaase** [comment]
This issue is now fixed:
* I set up a .php_cs.dist file 
* Fixed the code according to the rules
* Integrated it into the CI
