### ISSUE TITLE
Where is Struct instanciated?

### ISSUE THREAD

**Issue by Chemaclass** [jenshaase/phel-lang#25]
@jenshaase, I'm trying to find the usages of the `Struct` abstract class. 
```php
namespace Phel\Lang;
abstract class Struct extends Table {/* ... */}
```

And the only place where I found this class being used is in the Printer, in order to print the correct type:
```php
// in Phel\Printer::print() function
final class Printer
{
    public function print($form, bool $readable): string 
    {
        // ...
        if ($form instanceof Struct) {
            return $this->printStruct($form, $readable);
        }
        // ...
    }
    private function printStruct(Struct $form, bool $readable): string
    {/* ... */}
}
```

Being `Struct` an abstract class, it can not be instantiated on its own (by `new Struct`).
I didn't see any other class extending this abstract class as well. So the question is the following:
**Q**: What's the purpose of this `abstract class Struct` then?

**Comment by jenshaase** [comment]
Concrete classes of `Struct` are created by the Phel compiler using `defstruct` / `defstruct*`. Have a look at this test: https://github.com/jenshaase/phel-lang/blob/master/tests/php/Fixtures/Def/defstruct.test

**Comment by jenshaase** [comment]
@Chemaclass Can I close this issue?
