### ISSUE TITLE
Getting started - The namespace is not valid

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#26]
While going though the documentation I've encountered this error right at the start:

```
The namespace is not valid. A valid namespace name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. Elements are splitted by a backslash.
in /home/mabasic/code/src/test/hello-world/src/boot.phel:1

1| (ns hello-world\boot)
       ^^^^^^^^^^^^^^^^
```

When I change in file `src/boot.phel` this line `(ns hello-world\boot)` to `(ns hello_world\boot)`, the error goes away, but I am assuming that there is something wrong here..

Are the docs outdated or is there an error in namespace resolution? 

If it is the docs, I can submit a PR if you want.

**Comment by jenshaase** [comment]
Thank for reporting this.

For now, I would say that this is a bug in the documentation. I had to restrict namespaces to the form of PHP namespaces. But I think it would be better to support namespaces with a `-`.

If you want, you can make a pull request to fix the documentation. I the meantime, I can have a look if it is possible to have namespaces with a `-`.

**Comment by jenshaase** [comment]
I fixed this now. Namespaces with a dash are now supported and namespaces with a underscore throw an error. I also updated the documentation regarding the naming conventions:

"A valid namespace name starts with a letter, followed by any number of letters, numbers, or dashes. Individual parts of the namespace are seperated by the `\` character. "

No more need to update the Getting started documentation

**Comment by mabasic** [comment]
Great news! I've just tested it and it works.

P.S. For some reason, my email reply in which I said that I will send a PR for the documentatio did not go through. nvm.

P.S.S. Is there a place where I can ask you questions regarding the language. I find the language very interesting.

**Comment by jenshaase** [comment]
Hi, I just created a gitter room: https://gitter.im/phel-lang/community
