### ISSUE TITLE
Make alternatives for __DIR__ and __FILE__

### ISSUE THREAD

**Issue by jenshaase** [jenshaase/phel-lang#31]
Since Phel is compiled to PHP files that are saved at other locations as the original file, a replacement for PHP Magic Constants __DIR__ and __FILE__ is required.

**Comment by jenshaase** [comment]
Fixed this issue. See documentation for more information: https://phel-lang.org/documentation/php-interop/

**Comment by mabasic** [comment]
This works, I have updated my lumen demo app. You can see it here: https://github.com/mabasic/phel-lumen-demo/blob/master/src/boot.phel
