### ISSUE TITLE
:use in namespace does nothing

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#34]
This code runs correctly:

```
(ns hello-world\boot)

(def app (php/new \Laravel\Lumen\Application "/home/mabasic/code/src/test/hello-world/"))

(php/-> app (run))
```

This code also runs correctly:

```
(ns hello-world\boot
    (:use \Laravel\Lumen\Application))

(def app (php/new \Laravel\Lumen\Application "/home/mabasic/code/src/test/hello-world/"))

(php/-> app (run))
```

What is the purpose of `(:use \Laravel\Lumen\Application)` if the file runs either way?

I was expected to get an exception or error if the php class was not included with `:use` in the file.

**Update**: Does `(:use \Laravel\Lumen\Application)` mean that I can reference that class by just using `Application`. If so, how can I alias it to something else? Also, how do I use a imported phel library? Did I miss that in the documentation?

**Comment by jenshaase** [comment]
> Update: Does (:use \Laravel\Lumen\Application) mean that I can reference that class by just using Application.

Correct. You can just use `Application` now. You can also define an alias:

```
(ns hello-world\boot
  (:use \Laravel\Lumen\Application :as MyAlias))
```

> Also, how do I use a imported phel library? Did I miss that in the documentation?

Instead of `:use` you need to use `:require`.

```
(ns hello-world\boot
  (:require hello-world\test))

# Call a function in test
(test/my-fn)
```

Alias is also supported

```
(ns hello-world\boot
  (:require hello-world\test :as something))

# Call a function in test
(something/my-fn)
```

The documentation definitely needs some update on this topic!

**Comment by mabasic** [comment]
Thank you for explaining. On it :)
