### ISSUE TITLE
Improve documentation for namespaces

### ISSUE THREAD

**Issue by jenshaase** [jenshaase/phel-lang#35]
Explain `:use` and `:require` in more detail:

* What are the difference
* How to set aliases
* How to use aliases

**Comment by mabasic** [comment]
Can I give this a go?

**Comment by jenshaase** [comment]
Go ahead. Please add it to the Namespaces chapter!

**Comment by mabasic** [comment]
Question: How do you use Phel modules that you import?

eg.

```
(ns hello-world\boot
    (:require hello-world\util))

(util greet "name")
(hello-world\util greet "name")
```

**Comment by jenshaase** [comment]
This way:

```
(ns hello-world\boot
    (:require hello-world\util))

(util/greet "name")
```

**Comment by mabasic** [comment]
Can't get it to work.

`src/util.phel`:

```
(ns hello-world\util)

(print "Hello Utilities")

(defn greet
    "It greets the person with given name"
    [name]
    (str "Hello" name))
```

`src/boot.phel`:

```
(ns hello-world\boot
    (:require hello-world\util))

(print "Hello World!")

(util/greet "Mario")
```

**Comment by jenshaase** [comment]
Found a bug and fixed it in the last commit.

**Comment by mabasic** [comment]
`@{:private true}` does nothing when defined with defn or def.

eg.

```
(def my-name @{:private true :doc "This is my name."} "Mario")

(defn greet
    "It greets the person with given name"
    @{:private true}
    [name]
    (str "Hello, " name))
```

I can still access those functions/values when using :require in another .phel file. What is the purpose of :private true?

**Comment by mabasic** [comment]
@jenshaase Is it possible to import a module that is in a different namespace without first loading that namespace in index.php?

eg.

```
(ns hello-world\boot
    (:require hello-mars/boot)
```

**Comment by jenshaase** [comment]
> If I add $rt->addPath('hello-mars\\', [__DIR__ . '/../mars']); to src/index.php then I can use it.

Correct. That's need to be added.
