### ISSUE TITLE
Make shortcut/alias for PHP superglobals

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#41]
See here: https://www.php.net/manual/en/language.variables.superglobals.php

Maybe `$_REQUEST` could be a function called `(request ...)`. 

Just (request ...) is probably bad :) ?

They should resolve to `(get php/$_REQUEST "my-param")` or similar.

**Comment by jenshaase** [comment]
Fixed this issue by adding a `phel\http` module that creates a request struct. See documentation: https://phel-lang.org/documentation/http-request/

**Comment by mabasic** [comment]
Very nice. Going to try it out.

**Comment by mabasic** [comment]
@jenshaase The usage part is not very clear to me.

I am trying to get the method from the request:

```
(print (get (http/request-from-globals) :method))
```

Is this the correct way to use this?

First I have to call `(http/request-from-globals)`, then I need to use `(get ... :field)` ?

**Comment by jenshaase** [comment]
Yes exactly. In general, there are multiple way to do it

```
(def request (http/request-from-globals))
(println (get request :method))
```

```
(let [request (http/request-from-globals)]
  (println (get request :method)))
```

```
(let [{:method m} (http/request-from-globals)]
  (println m))
```

**Comment by mabasic** [comment]
I see. Thank you.
