### ISSUE TITLE
Run phel script from the command line

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#45]
I don't know if this is possible atm, but it would be nice to be able to execute phel scripts from the command line.

eg.

```
vendor/bin/phel ./boot.phel
```

Is this possible?

I could give this a try to implement if you want?

**Comment by Chemaclass** [comment]
I was wondering the exact same thing 🤔 
I think that would be awesome.

**Comment by jenshaase** [comment]
There is a another missing feature. Currently you have to configure the `Runtime` by calling `addPath`. This needs to be done for every namespaces. If you want to use multiple Phel libraries with different namespaces you have to do that manually right now.

There needs to be a feature like `composer dump-autoload` that does that automatically. Therefore, every package needs to have some configuration to configure the source locations (similar to the "autoload" configuration in composer.json).

I'm not sure where to put this configuration currently. Either in a separate file call `phel.json` (like this one https://github.com/jenshaase/phel-lang/blob/master/phel.json) or in the `composer.json` file (the "extra" options can be used for custom cases).

If this is implement it is rather easy to implement a `run` command.

**Comment by mabasic** [comment]
> There is a another missing feature. Currently you have to configure the `Runtime` by calling `addPath`. This needs to be done for every namespaces. If you want to use multiple Phel libraries with different namespaces you have to do that manually right now.

I think that this also relates to my question here: https://github.com/jenshaase/phel-lang/issues/35#issuecomment-643631421

**Comment by mabasic** [comment]
> There is a another missing feature. Currently you have to configure the `Runtime` by calling `addPath`. This needs to be done for every namespaces. If you want to use multiple Phel libraries with different namespaces you have to do that manually right now.
> 
> There needs to be a feature like `composer dump-autoload` that does that automatically. Therefore, every package needs to have some configuration to configure the source locations (similar to the "autoload" configuration in composer.json).
> 
> I'm not sure where to put this configuration currently. Either in a separate file call `phel.json` (like this one https://github.com/jenshaase/phel-lang/blob/master/phel.json) or in the `composer.json` file (the "extra" options can be used for custom cases).
> 
> If this is implement it is rather easy to implement a `run` command.

Since we are already using `composer.json` it would be nice not to create a separate file `phel.json` for this. What do you think? How much work is needed for this?

**Comment by jenshaase** [comment]
This is now working.

```
vendor/bin/phel run path/to/file.phel
# or
vendor/bin/phel run my-namespace\module
```

**Comment by mabasic** [comment]
Super cool. Can't wait to test it.

**Comment by mabasic** [comment]
@jenshaase Running `vendor/bin/phel run my-namespace\module` does not work, but running `vendor/bin/phel run "my-namespace\module"` does work.

Running `vendor/bin/phel run path/to/file.phel` works.
