### ISSUE TITLE
Improve 'Comparison operation' documentation

### ISSUE THREAD

**Issue by JesusValera** [jenshaase/phel-lang#49]
From my point of view, the [`Comparison operation`](https://phel-lang.org/documentation/truth-and-boolean-operations/) section is not clear enough.

```
<= Check if all given values are in a non-descending order. Returns a boolean.
<  Check if all given values are in ascending order. Returns a boolean.
>= Check if all given values are in non-ascending order. Returns a boolean.
>  Check if all given values are in descending order. Returns a boolean.
```

Investigate if something like that is more understandable.
```
<= Check if all given values are in ascending order (repeat values are not allowed). Returns a boolean.
<  Check if all given values are in ascending order (repeat values are allowed). Returns a boolean.
>= Check if all given values are in descending order (repeat values are not allowed). Returns a boolean.
>  Check if all given values are in descending order (repeat values are allowed). Returns a boolean.
```

**Comment by Chemaclass** [comment]
I like the idea of unifying `ascending` and `descending `. But, why `(repeat values are not allowed)`?

**Comment by JesusValera** [comment]
> I like the idea of unifying `ascending` and `descending `. But, why `(repeat values are not allowed)`?

You are right, probably someone can think repeated values are forbidden.
Maybe fits better: `(repeat values will return false)`

What do you think?

**Comment by Chemaclass** [comment]
I don't understand what's the problem with "repeated values" and why they need to be "remarked" as special ones.
```
 # using "<"
(< 1 2 3) === (1 < 2 < 3) # true
(< 2 2 2) === (2 < 2 < 2) # false

 # using "<="
(<= 1 2 3) === (1 <= 2 <= 3) # true
(<= 2 2 2) === (2 <= 2 <= 2) # true
(<= 2 2 3) === (2 <= 2 <= 3) # true
(<= 2 2 1) === (2 <= 2 <= 1) # false
```
The repeated values depend on their context in the same way as other numbers by using a specific operator. I don't think we need to "mark" them as especial numbers. Or am I missing something?

**Comment by JesusValera** [comment]
The idea is to remark that `<` and `<=` are not equals.
```
(< 1 2 3) # true
(<= 1 2 3) # true
---
(< 1 2 3 3) # false
(<= 1 2 3 3) # true
```
If we removed the `repeated values`, the sentence would be:
`Check if all given values are in ascending order`
That's why I put the `repeated` sentence.

Do you think is more clear as it is currently? :arrow_down: 
```
<= Check if all given values are in a non-descending order. Returns a boolean.
<  Check if all given values are in ascending order. Returns a boolean.
```

**Comment by Chemaclass** [comment]
What about this?
```
<= Check if all given values are in ascending (or equal) order. Returns a boolean.
<  Check if all given values are in ascending order. Returns a boolean.
>= Check if all given values are in descending (or equal) order. Returns a boolean.
>  Check if all given values are in descending order. Returns a boolean.
```

**Comment by jenshaase** [comment]
Why not this:
```
<= Checks if each argument is less than or equal to the following argument. Returns a boolean.
<  Checks if each argument is is strictly less than the following argument. Returns a boolean.
>= Checks if each argument is greater than or equal to the following argument. Returns a boolean.
>  Checks if each argument is strictly greater than the following argument. Returns a boolean.
```

I this this is much cleaner.

**Comment by JesusValera** [comment]
Hmm, I would pick @Chemaclass suggestion, This is cleaner for me.
What do you think @mabasic?

**Comment by mabasic** [comment]
Considering that both suggestions are perfectly valid and the reader would understand both it does not matter which one is picked.

After reading both for the first time, I must admit that I find the one @jenshaase wrote last to be simpler to me personally. Ascending and descending always confuses me at first 😁.

**Comment by jenshaase** [comment]
@JesusValera This can be closed now. Correct?
