### ISSUE TITLE
Add a set data structure

### ISSUE THREAD

**Issue by jenshaase** [jenshaase/phel-lang#5]
Currently Phel has Tuples, Arrays and Tables. It would be nice to have a Set data structure based on PHP Arrays. For example:
```
(set :a :b :c)
```

Methods on a set:
* union
* intersection
* difference
* join

**Comment by paullaffitte** [comment]
Actually there is already an implementation of [Set](https://www.php.net/manual/fr/class.ds-set.php) in PHP with the methods you quoted. Why not just use this instead of arrays?

**Comment by jenshaase** [comment]
Thank @paullaffitte! I know of this. However, this is part of a separate module and these modules are mostly not part of cheap hosting providers. Therefore, I would go for a custom implementation based of PHP Arrays, just like the `Table` and `PhelArray`.

**Comment by paullaffitte** [comment]
Oh ok I see. Should I consider performances in the first implementation or do you prefer to have something working quickly and improve its perfs later on?

**Comment by jenshaase** [comment]
Regarding performance there are two aspects.

- Runtime performance: This should as good as PHP itself because the code is compiled to PHP and than executed. The only thing that is slowing down are sub optimal implementations of the core libraries.
- Compile time performance: This is the time the compiler needs to compile the program. If optimized it already, but PHP currently has it's limitations on this one. However, PHP 8 is on it's way and is coming with an JIT Compiler. This improves the compile time of Phel drastically.

If you have more questions on that, consider making a new issue.

**Comment by jenshaase** [comment]
Closed with PR #62
