### ISSUE TITLE
Proposal: Autogenerated Runtime

### ISSUE THREAD

**Issue by jenshaase** [jenshaase/phel-lang#52]
This issue is a proposal for a autogenerated `Runtime` class that make its much easier to get started with Phel.

# Motivation

Currently the `Runtime` needs to be configured manually. All paths of all libraries need to be added to the configuration. This can be a frustrating job when the amount of library increases or the libraries change their paths.

# Concept

To resolve this problem, a `Runtime` configuration should be automatically generated from the installed Composer plugins. This is already done by Composer its self for PHP's autoloading standards (PSR-4, PSR-0, etc.). Composer offers a Plugin System for exactly such a purpose. (https://getcomposer.org/doc/articles/custom-installers.md)

High level view: Whenever Composer updates or installs a dependencies a new `Runtime` configuration file is written and saved to `vendor/PhelRuntime.php`. The file looks like this

```php
<?php

// @generated by Phel
use Phel\Runtime;

require __DIR__ .'/autoload.php';

$rt = Runtime::initialize();
$rt->addPath("hello-world\\", [__DIR__ . '/../src/']);
$rt->addPath("phel\\", [__DIR__ . '/phel/phel/src/phel/']);
// More addPath

$rt->loadNs("phel\\core");
return $rt;
```

Given this file, the `index.php` (to run the application) can that be changed to

```php
<?php

$rt = require __DIR__ .'/../vendor/PhelRuntime.php';
$rt->loadNs('hello-world\boot'); // Load the namespace to start the application
```

Additionally, it is now much easier to make a `run` command for the `phel` cli.

```
./vendor/bin/phel run /path/to/file.phel
# or
./vendor/bin/phel run hello-world\my-namespace
```

# Requirements

In order to archive this, each library needs to provide a configuration with a namespace. I will suggest that we will put this configuration in the `composer.json` file under `extra.phel`.

```json
{
    "extra": {
        "phel": {
            "loader": {
                "phel\\": "src/phel/"
            },
            "loader-dev": {
                "phel\\": "tests/phel/"
            }
        }
    }
}
```

Putting Phel's configuration in the `composer.json` file has the advantage that looking for all library configuration is quite easy, because all package configurations are collected into `composer.lock`. I choosed the `extra` section of composer, because it is the only section in which composer allows custom configurations (see https://getcomposer.org/schema.json).

# Alternative

An alternative would be to put the configuration into a extra file, called `phel.json`. This has the advantage the we are independent of the composer specs. The drawback is that have to collect the `phel.json` files manually. Also, it may be required that we need to read the composer.json file from each Phel package anyway.

# Drawbacks

To make it work, we need to change/add the following:

* In Phel's composer.json we need to change `"type": "library"` to `"type": "composer-plugin"`.
* A requirement needs to be added: `composer-plugin-api`

# Documentation

* A documentation for the "phel" configuration section needs to be written
* The Getting Started Guide must be changed
* A documentation for Library-Developers would be great.

**Comment by mabasic** [comment]
I like everything about this proposal, except the part where it is needed to set package type to `composer-plugin`. 

I don't know the exact drawbacks of it, but this (main phel repository) is most definitely not a composer plugin, but a library of sort. 

Would it be possible to create a new repository (let's call it for example `phel-composer-plugin`), set its type to `composer-plugin`, add the dependency there, and then require that package in this repository. That way this repo can stay as `library`, and we can easily change or add to that functionality.

What do you all think? Is this unnecessary?

**Comment by Chemaclass** [comment]
I know that composer is (and might still be) the trend nowadays, but what if it doesn't in the future? 
See for example this other project PHIVE https://phar.io/

I would prefer to decouple from the composer creating our own `phel.json` configuration. 
For the autoload part we might consider using another tool: https://github.com/theseer/Autoload This is `a lightweight php namespace aware autoload generator and phar archive builder` (done by the author of PHIVE as well).

I would suggest taking a look at these tools. I would avoid at all having phel as "composer-plugin-api" :)

**Comment by jenshaase** [comment]
Is PHIVE a dependency manager? For me it is just a tool to replace the "require-dev" section of composer.

https://github.com/theseer/Autoload Is just for autoloading PHP classes.I was speaking of loading Phel modules.

I prefer the Composer only way for now, because it makes getting started with Phel so much easier and it is not a lot of work to do. Building a solution that works with multiple dependency manager on the other side makes it a little harder to get started and also requires a little bit more implementation work. Don't get be wrong, I will be happy to support multiple dependency managers but I think this can be done when Phel has more traction and there is a real need for it.

**Comment by Chemaclass** [comment]
Yes, PHIVE is a dependency manager where you track the complete version of the tools that your app depends on. Try it out :)
On the other hand, I agree with you @jenshaase, we should focus on an MVP that works and later on keeping improving within small iterations.

**Comment by jenshaase** [comment]
Thanks for your feedback.

I think we can go this way:
* Make a new git repository: `phel-composer-plugin`
* This repository contains only the code of the composer plugin
* The plugin is then used as a dependency in Phel
* I will read the configuration from the "composer.json" "extra" section.

**Comment by mabasic** [comment]
I can help write documentation for this once implemented, and test it out.

**Comment by jenshaase** [comment]
Implementation is more or less done: https://github.com/jenshaase/phel-composer-plugin

I also added it as dependency to Phel and tested it with a sample project. Make sure you add `"minimum-stability": "dev"` to your tests-project's composer file. Otherwise you will get an error.

If you don't find any bugs, we can update the documentation.

**Comment by mabasic** [comment]
Wow that is fast. Can't wait to test it out.

**Comment by mabasic** [comment]
@jenshaase Tested it. Works perfectly! 

It is much simpler now to use multiple namespaces in a single package. Using other packages is also seamless. Can we proceed now with the cli part #45 ?

**Comment by jenshaase** [comment]
I will close this issue now, because @mabasic make individual issues for the rest of the work.
