### ISSUE TITLE
Proposal: Renaming Phel class

### ISSUE THREAD

**Issue by Chemaclass** [jenshaase/phel-lang#56]
## Context

Let's consider this code:

```php
// namespace: Phel
// class: Analyzer

/** @param Phel|scalar|null $x */
public function analyze($x, NodeEnvironment $env): Node
{
    if ($this->isLiteral($x)) {
        return new AnalyzeLiteral;
    }
    if ($x instanceof Symbol) {
        return new AnalyzeSymbol;
    }
    if ($x instanceof Tuple && $x->isUsingBracket()) {
        return new AnalyzeBracketTuple;
    }
    if ($x instanceof PhelArray) {
        return new AnalyzeArray;
    }
    if ($x instanceof Table) {
        return new AnalyzeTable;
    }
    if ($x instanceof Tuple) {
        return new AnalyzeTuple;
    }
    throw new AnalyzerException('Unhandled type: ' . var_export($x, true));
}
```

When I read this code I think:
<<<
* The namespace `Phel` it makes sense because it might be considered the root of the project named `Phel`. 
* The class name `Analyzer` is also straight forward. 
* The methods `analyzeInEmptyEnv()` and `analyze()` are also easy to understand

But wait for a second, what type is `$x` again? `/** @param Phel|scalar|null $x */`

<<<

`$x` can be `null,` any `scalar` **AND** a `Phel` type? What does `Phel` in this context mean?

These are the "`Phel's` children":
* `Symbol`
* `Tuple`
* `PhelArray`
* `Table`

## The Phel class

```php
<?php
namespace Phel\Lang;

abstract class Phel implements IMeta, ISourceLocation
{
    use TSourceLocation;
    use TMeta;

    /** Check if the value is truthy */
    abstract public function isTruthy(): bool;

    /** Computes a hash of the object */
    abstract public function hash(): string;

    /** @param mixed $other The other value. */
    abstract public function equals($other): bool;
}
```

## The question

What does "Phel" as an **abstract class** mean? 
Why am I saying this? Because it seems a bit confusing, especially the first time when you look at this type `Phel` (knowing as well that the project/language name is `Phel` too).

## Proposal

Wouldn't it be better to rename this (abstract) class to something more accurate to its meaning? 
What about renaming `Phel` to `DataType`, for example? 
Any other suggestion is more than welcome :)

**Comment by jenshaase** [comment]
Hi,

its a good idea to rename `Phel`. I would suggest either `Type` or `AbstractType`.

Just for explanation why some of the types are `Phel|null|scalar`. The union of these are all types that are supported by the Phel language.

* Phel's boolean is a PHP boolean (scalar)
* Phel's string is a PHP string (scalar)
* Phel's int and floats are equal to PHP's int and float (scalar)
* Phel's nil is represented by PHP's null
* All other Phel types extend the `Phel` class. These are currently `Symbol`, `Keyword`, `Tuple`, `PhelArray`, `Table` and `Struct`

If I would have designed this language independently from PHP, all these types would extend one common root type. This is done in many other languages. For examples, all Java classes extends from `java.lang.Object`.

In a first draft of my implementation I wrapped strings, boolean int and floats in objects. So I had the classes PhelString, PhelInt, PhelFloat and PhelBoolean. However, this made it much more complex and added a lot of bugs and undefined behaviors.

The optimal solution would be, if PHP would support type aliases (e.g. as in Typescript).

I hope that this makes it a bit clearer.

**Comment by Chemaclass** [comment]
Great explanation! I get it. I like the idea of `AbstractType` much more than just `Phel`, but what about `PhelType`?

Anyway, either `AbstractType` or `PhelType` are both good names in my opinion. @jenshaase, you pick one and I will create a PR with the renaming :)

---

About the `PhelString`, `PhelInt`, `PhelFloat` and `PhelBoolean`... yeah, it's a good topic, but I don't have right now a proper solution or proposal for this one. As you said, the optimal might be type aliases. 
Actually, considering this:
```php
public function analyze(?PhelType $x, NodeEnvironment $env): Node {/*...*/}
```
the type of `$x` is really explicit (there is even no need for PHPDoc). I will think about it a little bit too, but that's out of the scope of this proposal.

**Comment by jenshaase** [comment]
Let's rename to `AbstractType`
