### ISSUE TITLE
RuntimeException: Cannot load namespace: hello-worldboot

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#60]
Running `vendor/bin/phel run hello-world\boot` does not work, but running `vendor/bin/phel run "hello-world\boot"` does work.

This is the output that I get when running `vendor/bin/phel run hello-world\boot`:

```
RuntimeException: Cannot load namespace: hello-worldboot
in /home/mabasic/code/src/test/hello-world/vendor/phel/phel/src/php/Commands/Run.php:36 (gen: /home/mabasic/code/src/test/hello-world/vendor/phel/phel/src/php/Commands/Run.php:36)

PHP Notice:  Undefined index: args in /home/mabasic/code/src/test/hello-world/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 106
PHP Warning:  Invalid argument supplied for foreach() in /home/mabasic/code/src/test/hello-world/vendor/phel/phel/src/php/Exceptions/TextExceptionPrinter.php on line 149
#0 /home/mabasic/code/src/test/hello-world/vendor/phel/phel/src/php/phel.php(52): Phel\Commands\Run->run()
#1 /home/mabasic/code/src/test/hello-world/vendor/phel/phel/phel(4): require_once('/home/mabasic/c...')
```

**Update**: When I use double backslash then it works: `vendor/bin/phel run hello-world\\boot`.

**Comment by jenshaase** [comment]
Yes you need to wrap it in quotes or use the double backslash. I forgot to mention this in #45. The backslash is an escaping character in bash/shell.

I will close this issue as there is no way to make `vendor/bin/phel run hello-world\boot` work.

**Comment by mabasic** [comment]
Is there a way to suppress the output when running `vendor/bin/phel run hello-world\boot` to just output "RuntimeException: Cannot load namespace: hello-worldboot" without the extra parts about the source code?
