### ISSUE TITLE
Bug: Comparaison with 1

### ISSUE THREAD

**Issue by paullaffitte** [jenshaase/phel-lang#63]
# Observation

Comparing anything truthy with `1` will produce `true` as a result, but if compared with any other number it will produce `false`.

## Examples

All those lines will output `true`
```phel
(print (= 1 @["foo"]))
(print (= 1 ["foo"]))
(print (= 1 :a))
(print (= 1 @{:a "foo"}))
```

But those will output `false`
```phel
(print (= 1 nil))
(print (= :a @["foo"]))
```

The last one is the most surprising since `1 == :a` and `1 == @["foo"]`, so we could expect that `:a = @["foo"]`

# Expected behavior

We could expect that if something has a different type than something else, they cannot be equals. Or than every truthy numbers equals truthy values.

Moreover, we could expect that the equality respects the [basic properties of mathematical equality](https://en.wikipedia.org/wiki/Equality_(mathematics)#Basic_properties) (substitution, reflexive, symmetric and transitive properties). With the last example (`(= :a @["foo"])`) we can see that the transitive property is not respected.

**Comment by Chemaclass** [comment]
I think this is something related to PHP behavior: https://phel-lang.org/documentation/truth-and-boolean-operations/
* In Phel `=` is in PHP `==`
* In Phel `id` is in PHP `===`

**Comment by jenshaase** [comment]
@Chemaclass is correct. This is a PHP specific behavior. Whats happening here is call "Type Juggling" (https://www.php.net/manual/de/language.types.type-juggling.php). This converts the types automatically to the "correct" value. The comparison operator in PHP is defined the following way:

> $a == $b is TRUE if $a is equal to $b **after** type juggling.


```
(= 1 @["foo"]) # Number 1 is converted to true, a Phel array is a PHP object, PHP objects are true, hence the output is true
(= 1 ["foo"]) # Same as above (Tuple is PHP Object)
(= 1 :a) # Same as above (Keyword is PHP Object)
(= 1 @{:a "foo"}) # Same as above (Table is PHP Object)

(= 1 nil) # Number 1 is converted to true, nil is equal to PHP null, which evaluates to false
(= :a @["foo"]) # Both are object. But in this case PHP checks if objects have the same type.
```

But this a behavior that we can change in Phel to make it better. I would propose that only `nil` and `false` evaluate to `false`. Everything else evaluates to `true`. Even `0`, the empty string, empty arrays and empty tables will evaluate to `true`. If you still need PHP's equal behavior you can call `(php/== ...)` or `(php/=== ...)`

What do you think?

**Comment by Chemaclass** [comment]
I like this idea. It's actually how [Clojure](https://clojuredocs.org/clojure.core/boolean) currently behaves:
* returns `false` for `false` and `nil`.
* returns `true` for everything else.

**Comment by paullaffitte** [comment]
I like the idea too, nevertheless, I found confusing the fact that 0 would evaluate to true. Does it means that `(print (if 0 "true" "false"))` would output "true"? However, for the empty string/array/table, I can understand this point of view.

**Comment by jenshaase** [comment]
Fixed this issue. It was quite helpful to redefine this. As side-effect I found some bugs in the library :)
