### ISSUE TITLE
Docs: Wrong definition of a function

### ISSUE THREAD

**Issue by paullaffitte** [jenshaase/phel-lang#64]
# Observation

In the section of the doc about [Functions and Recursion](https://phel-lang.org/documentation/functions-and-recursion/), and more precisely about Anonymous Function, you can find this example:

```
(fn [] 1 2 3) # A function that returns 3
```

But this code results in this error: "'fn requires one or two arguments".

# Expected behavior

I'm not sure about what is the expected behavior, I'm just sure that the doc is wrong about this. So maybe someone more experimented on the project than me could help me to determine the expected behavior.

**Comment by jenshaase** [comment]
Thanks for reporting this!

Instead of fixing the documentation, I fixed `fn`. `fn` supports now multiple elements and only the last one is returned. Same applies for `defn`.
