### ISSUE TITLE
Bug: Require a module

### ISSUE THREAD

**Issue by paullaffitte** [jenshaase/phel-lang#66]
# Observations

It seems that sometimes, modules aren't correctly resolved.

First, if I require a module that doesn't exists, the program will just ignore it without any warning neither error. Second, as you can see in #65, I cannot require the module `phel\test\http` from `phel\test\index`. But if I remove the require statement to `phel\http` in `phel\test\http`, it works again. I've tried to use the keyword `:as`, but it didn't change anything. So I'm suspecting a conflict of name maybe.

# Expected behavior

I want to get an error if I require a module that doesn't exist. And I should be able to require `phel\test\http` from `phel\test\index`.

**Comment by jenshaase** [comment]
I have to investigate this issue. Seems to be a bigger problem.

**Comment by jenshaase** [comment]
Fixed this issue.
