### ISSUE TITLE
Bug: Reduce cannot be used on a set whereas map can

### ISSUE THREAD

**Issue by paullaffitte** [jenshaase/phel-lang#79]
## Description

Using `reduce` or `reduce2` on a set will output the following error: `Cannot use object of type Phel\Lang\Set as array`. But using map on a set is perfectly fine and work as expected. This is because the function `first` is used in the implementation of reduce
, which is used in the implementation of `reduce2`.

For reduce2 there is another catch, a set cannot be destructured becase the syntax `[x & xs]` is only supported by arrays. Here it could make sense to make this feature available for `Iterators` since it doesn't say that it will take the _first_ element, it only says that it will take _one_ element (`Iterator::current`) and the rest of it (`Iterator::next`).

## Expected behavior

Since a set is an unordered data structure, it make sense that we cannot use `first` on it. So I think to solution is to make `reduce` Iterator-compatible by removing this function from its implementation and allowing this syntax `[x & xs]` for `Iterators`.

**Comment by jenshaase** [comment]
Good catch. I will investigate this issue.

**Comment by paullaffitte** [comment]
And btw, `next` seems to be only callable on arrays (and ICdr) too 😅

**Comment by jenshaase** [comment]
I fixed this issue. Every data structure now implements `ISeq`, which has the methods `first`, `rest` and `cdr`.
