### ISSUE TITLE
Bug: Core tests are warning about something wrong

### ISSUE THREAD

**Issue by Chemaclass** [jenshaase/phel-lang#83]
## Bug

These tests (in `tests/core.phel`) are displaying an **NOTICE error:**

```clojure
(assert (= (set 1 2 3) (push (set 1 2) 3)) "set push")
(assert (= (set 1 2) (push (set 1 2) 2)) "set push existing value")
```
Output:
```
Notice: Only variables should be passed by reference in /private/var/folders/qq/v42dxsw95cv30dt79r7b2dbr0000gn/T/__pheloqcXU6 on line 4
PHP Notice:  Only variables should be passed by reference in /private/var/folders/qq/v42dxsw95cv30dt79r7b2dbr0000gn/T/__pheloqcXU6 on line 4
```

## How can I reproduce it?

You can verify it by commenting these lines out (by adding `#` at the very beginning of the line) and running the tests again (using `composer test-core`); that NOTICE will be gone.

I think it might not be related to the sets but with the push... This needs some investigation.

**Comment by jenshaase** [comment]
I fixed this the test. The `push` function takes a reference argument. In PHP it would look like this:

```php
<?php
function push(&xs) { ... }
```

Therefore PHP prints this notice. I need to do this to support PHP array in this call. Otherwise, PHP arrays will be copied to the method.

**Comment by Chemaclass** [comment]
Cool, thanks!
