### ISSUE TITLE
Add syntax support for PhpStorm

### ISSUE THREAD

**Issue by Chemaclass** [jenshaase/phel-lang#88]
### Current behavior

We have currently syntax support for `vscode` (as a plugging inside `editor-support/vscode`).

### Definition of Done

Create something similar for PhpStorm.

#### Some help

* https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started.html
* https://github.com/JetBrains/intellij-platform-plugin-template
* https://confluence.jetbrains.com/display/PhpStorm/Plugin+Development
* https://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support.html
* https://github.com/gregsh/Clojure-Kit

**Comment by jenshaase** [comment]
Has anyone experience on this topic? I'm probably not able to maintain such a plugin within this project. Maybe this can be separate project?

**Comment by Chemaclass** [comment]
I don't have experience with that, but I use PhpStorm and I would like to try to do this one! Assign it to me and I will try to get some time for this :)

**Comment by jenshaase** [comment]
Ok. If it helps, I already built two types of syntax definitions. The first one is in the TextMate Format and the second one is in the Sublime Format:

* https://github.com/jenshaase/phel-lang/blob/master/editor-support/vscode/syntaxes/phel.tmLanguage.json
* https://github.com/jenshaase/phel-lang/blob/master/doc/syntaxes/phel.sublime-syntax

**Comment by jenshaase** [comment]
@Chemaclass Are you still planning to work on this. Otherwise I will close this issue

**Comment by Chemaclass** [comment]
Hey Jens, no, not really right now. I tried it, but it's more complex than I thought. I would prefer to focus on other more important tasks. We can close it 👍🏼

**Comment by Chemaclass** [comment]
I prepared a workaround to add syntax support for PhpStorm: https://github.com/phel-lang/phel-phpstorm-syntax
