### ISSUE TITLE
Namespace conflict when running tests

### ISSUE THREAD

**Issue by mabasic** [jenshaase/phel-lang#90]
- [x] Possible documentation mistake in testing and configuration?

Given this config in `composer.json`:

```
"extra": {
        "phel": {
            "loader": {
                "hello-world\\": "src/"
            },
            "loader-dev": {
                "hello-world\\": "tests/"
            },
            "tests": [
                "tests/"
            ]
        }
    },
```

And these files:

src/boot.phel:

```
(ns hello-world\boot)

(println "Hello, World!")
```

tests/boot.phel

```
(ns hello-world\boot
    (:require phel\test :refer [deftest is]))

(deftest test-variable
    (is (= 4 (+ 2 2))))
```

When running `vendor/bin/phel test`, I get:

```
Hello, World!

Passed: 0
Failed: 0
Error: 0
Total: 0
```

but when I rename the test file to `test.phel` (and update the namespace to match) or anything other than what a file is called in `src` directory it works.

```
.



Passed: 1
Failed: 0
Error: 0
Total: 1
```

As far as I understand we are telling people in the documentation to use `hello-world` namespace for both `loader` and `loader-dev`. That is why this is happening. I'm going to send a PR to change `loader-dev` namespace in the documentation to `hello-world\\tests\\`.

**Comment by jenshaase** [comment]
What would you want to happen in this case? Should there be a error? I think the same happens in PHP if you use the PSR-4 Autoloader. If you have two files with the same namespace in different location only the first one found is loaded.

**Comment by mabasic** [comment]
I think that by changing the documentatiom we have avoided this issue. 

Best to leave it alone for now because it is easy to catch the mistake. Maybe investigate a bit how it works in PHP.

**Comment by Chemaclass** [comment]
I'm with you @mabasic. This PR https://github.com/jenshaase/phel-lang/pull/92 was a great idea :)
